Biblioteca/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = "webapp"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("categories", views.categories, name="categories"),
    path("category_books", views.category_books, name="category_books"),
    path("authors", views.authors, name="authors"),
    path("author_books", views.author_books, name="author_books"),
    path("books", views.books, name="books"),
    path('books/datatable/', views.DataTableBooks.as_view(), name='books_table'),
]

webapp/models.py
from django.db import models
from django.contrib import admin


# Create your models here.
class Author(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = "Categories"


class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	categories = models.ManyToManyField(Category)
	file_format = models.CharField(max_length=10)
	pages = models.IntegerField()
	file = models.FileField()
	image = models.ImageField()

	def __str__(self):
		return self.title

webapp/views.py
from django.shortcuts import render
from webapp.models import Book, Category,  Author
from django.core.paginator import Paginator
from django.conf import settings
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.db.models import Q
from django.db.models import Count

# Homepage page
def homepage(request):
	books = Book.objects.all().order_by('?')[:8]
	template_name = "webapp/index.html"
	return render(request, template_name, {"books": books})

# Categories page
def categories(request):
    search_category = request.GET.get("search_category")
    if search_category:
        categories = Category.objects.filter(name__icontains=search_category).order_by('name')
    else:
        categories = Category.objects.all().order_by('?')
    paginator = Paginator(categories, 24)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template_name = "webapp/categories.html"
    return render(request, template_name, {"categories": page_obj, "search_category": search_category})


# Category books page
def category_books(request):
    category_name = request.GET.get('category_name')
    category = Category.objects.get(name=category_name)
    books = Book.objects.filter(categories=category).order_by('title').distinct()
    paginator = Paginator(books, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template_name = "webapp/category_books.html"
    return render(request, template_name, {"books": page_obj, "category":category})


# Authors page
def authors(request):
    search_author = request.GET.get("search_author")
    if search_author:
        authors = Author.objects.filter(name__icontains=search_author).order_by('name')
    else:
        authors = Author.objects.all().order_by('?')
    paginator = Paginator(authors, 24)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template_name = "webapp/authors.html"
    return render(request, template_name, {"authors": page_obj, "search_author": search_author})


# Author books page
def author_books(request):
    author_name = request.GET.get('author_name')
    author = Author.objects.get(name=author_name)
    books = Book.objects.filter(authors=author).order_by('title').distinct()
    paginator = Paginator(books, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template_name = "webapp/author_books.html"
    return render(request, template_name, {"books": page_obj, "author":author})


# All books page
def books(request):
    author = request.GET.get('author')
    category = request.GET.get('category')
    categories = Category.objects.all().order_by('name').distinct()
    template_name = "webapp/books.html"
    return render(request, template_name, {"categories": categories, "category": category, "author":author})


#Class for DataTable
class DataTableBooks(BaseDatatableView):
    model = Book
    columns = ['title','authors','categories','pages','file_format']
    order_columns = ['title', 'authors__name']
    max_display_length = 100

    def get_initial_queryset(self):
    	get_categories = self.request.GET.getlist("categories[]")
    	if len(get_categories) > 0:
            books = Book.objects.filter(categories__name__in=get_categories).annotate(count=Count('categories')).filter(count=len(get_categories)).distinct()
            return books
    	else:
            return Book.objects.all().distinct()

    def render_column(self, row, column):
        if column == 'authors':
            return "".join([" - "+a.name for a in row.authors.all()])
        elif column == "categories":
            return "".join([" - "+c.name for c in row.categories.all()])
        elif column == "title":
        	return f'<a href="{row.file}" target=_blank>{row.title}</a>'
        else:
            return super(DataTableBooks, self).render_column(row, column)


    def filter_queryset(self, qs):
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(Q(title__icontains=search) | Q(categories__name__icontains=search) | Q(authors__name__icontains=search)).distinct()
        return qs

webapp/templates/webapp/author_books.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}
    <title>BiblioMoteka - Autores</title>
{% endblock %}


{% block navbar %}
<a class="nav-link" href="{% url 'webapp:homepage' %}">Inicio</a>
<a class="nav-link" href="{% url 'webapp:categories' %}">Categorías</a>
<a class="nav-link active text-warning" aria-current="page" href="{% url 'webapp:authors' %}">Autores</a>
<a class="nav-link" href="{% url 'webapp:books' %}">Libros</a>
{% endblock %}

{% block content %}

<!-- Author -->
<div class="row justify-content-md-center p-3">
  <div class="col-6"> 
    <div class="card text-center border-warning border-2">
      <div class="card-body text-bg-dark">
          <h5>{{author.name}}</h5>
      </div>
    </div>
  </div>
</div>


<!-- Books -->
<div class="row row-cols-4 g-3 justify-content-md-center text-center" >
  {% for book in books %}
  <div class="col">
    <div class="card text-bg-dark border-warning border-2 h-100">
      {% if book.file_format == 'pdf' %}
      <div class="card-img-top p-3">
        <a href="{{ book.file }}" target="_blank"> <img src="{{book.image}}" width=150 height="200"> </a>
      </div>
      {% else %}
          <a class="text-decoration-none p-5" href="{{ book.file }}" target="_blank"><h6 align="center" class="card-title text-light">
          {% if book.file_format == 'epub' %}
            EPUB
          {% else %}
            DJVU
          {% endif %}
          </h6></a>
      {% endif %}
      <div class="card-body">
        <a class="text-decoration-none" href="{{ book.file }}"><h6 class="card-title text-light">{{book.title}}</h6></a>
        {% if book.file_format == 'pdf' %}
        <p class="text-secondary">{{ book.pages }} páginas</p>
        {% endif %}
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item text-secondary text-bg-dark border-warning">
          {% for author in book.authors.all %}
          - <a class="link-secondary" href="{% url 'webapp:author_books' %}?author_name={{author.name}}">{{ author.name }}</a>
          {% endfor %}
        </li>
        <li class="list-group-item text-secondary text-bg-dark border-warning">
          {% for category in book.categories.all %}
          #<a class="link-secondary" href="{% url 'webapp:category_books' %}?category_name={{category.name}}">{{ category.name }}</a>
          {% endfor %}
        </li>
      </ul>
      <a class="btn btn-warning rounded-0" href="{{ book.file }}" target="_blank">Enlace</a>
    </div>
  </div>
  {% endfor %}
</div>


<!-- Pagination-->
<nav aria-label="Pagination">
    <ul class="pagination justify-content-center p-3">

      {% if books.has_previous %}
      <li class="page-item"><a class="page-link" href="?author_name={{author.name}}&page={{ books.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&laquo;</a></li>
      {% endif %}

      {% for num in books.paginator.page_range %}
        {% if num == books.number %}
          <li class="page-item disabled"><a class="page-link"href="#">{{ num }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?author_name={{author.name}}&page={{ num }}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}

      {% if books.has_next %}
      <li class="page-item"><a class="page-link" href="?author_name={{author.name}}&page={{ books.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&raquo;</a></li>
      {% endif %}
    </ul>
</nav>
{% endblock %}

webapp/templates/webapp/authors.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}
    <title>BiblioMoteka - Autores</title>
{% endblock %}


{% block navbar %}
<a class="nav-link" href="{% url 'webapp:homepage' %}">Inicio</a>
<a class="nav-link" href="{% url 'webapp:categories' %}">Categorías</a>
<a class="nav-link active text-warning" aria-current="page" href="{% url 'webapp:authors' %}">Autores</a>
<a class="nav-link" href="{% url 'webapp:books' %}">Libros</a>
{% endblock %}

{% block content %}

<!-- Searchbox -->
<div class="row justify-content-md-center p-3">
  <div class="col-6">
    <div class="card text-center border-warning border-2">
      <div class="card-body text-bg-dark text-light">
        <input class="form-control" id="searchAuthor" aria-label="Search" placeholder="Búsqueda" data-url="{% url 'webapp:authors' %}"
          {% if search_author %}
            value="{{ search_author }}"
          {% endif %}
        ></input>
      </div>
    </div>
  </div>
</div>

<!-- Authors -->
<div class="row row-cols-4 g-3 justify-content-md-center text-center" >
  {% for author in authors %}
  <div class="col">
    <div class="card text-bg-dark border-warning border-2 h-100">
      <div class="card-body">
        <span class="card-title">{{author.name}}</span>
      </div>
      <a class="btn btn-warning rounded-0" href="{% url 'webapp:author_books' %}?author_name={{author.name}}">Ver libros
        <div class="card-link"></div>
      </a>
    </div>
  </div>
  {% endfor %}
</div>


<!-- Pagination-->
<nav aria-label="Pagination">
    <ul class="pagination justify-content-center p-3">
      {% if authors.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ authors.previous_page_number }}">&laquo;</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ authors.previous_page_number }}">{{ authors.previous_page_number }}</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&laquo;</a></li>
      {% endif %}
        
      <li class="page-item disabled"><a class="page-link"href="#">{{ authors.number }}</a></li>

      {% if authors.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ authors.next_page_number }}">{{ authors.next_page_number }}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ authors.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&raquo;</a></li>
      {% endif %}
    </ul>
</nav>
{% endblock %}


{% block links %}

<!-- Scripts for this page-->
<script language="JavaScript" type="text/javascript" src="{% static 'webapp/search_author.js' %}"></script>

{% endblock %}

webapp/templates/webapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
        <!-- Compiled and minified JavaScript -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script> 
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/dataTables.bootstrap4.min.js"></script>


        <!-- Favicon -->
        <link rel="icon" type="image/x-icon" href="">
        <!-- Title -->
        {% block title %}
          <title>Biblioteca - Base</title>
        {% endblock %}
    </head>

    <body class="bg-secondary">

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'webapp:homepage' %}">Biblioteca</a>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        {% block navbar %}
                            <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                            <a class="nav-link" href="#">Categorías</a>
                            <a class="nav-link" href="#">Autores</a>
                            <a class="nav-link">Libros</a>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </nav>

        <!-- Content -->
        <div class="container py-4">
              {% block content %}

              {% endblock %}
        </div>
    

    <!-- Footer -->
    <footer class="flex-shrink-0 py-4 bg-dark text-white-50 p-2" data-bs-theme="dark">
        <div class="container text-left">
            <div class="row">
                <div class="col l6 s12">
                    <h5>Contacto</h5>
                    <ul>
                        <li>Github: <a href="https://github.com/motellondev">https://github.com/motellondev</a></li>
                        <li>Email: <a href="mailto::motellondev@gmail.com">motellondev@gmail.com</a></li>
                        <li>Telegram: <a href="https://t.me/motellondev">https://t.me/motellondev</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


  {% block links %}
  {% endblock %}

</html>

webapp/templates/webapp/books.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}
    <title>Biblioteca - Libros</title>
{% endblock %}


{% block navbar %}
<a class="nav-link" href="{% url 'webapp:homepage' %}">Inicio</a>
<a class="nav-link" href="{% url 'webapp:categories' %}">Categorías</a>
<a class="nav-link" href="{% url 'webapp:authors' %}">Autores</a>
<a class="nav-link active text-warning" aria-current="page" href="{% url 'webapp:books' %}">Libros</a>
{% endblock %}



{% block content %}
<div class="card justify-content-md-center border-warning border-3">
  <div class="card-body" >
    <select class="form-select border-warning" id="filterBooks" aria-label="Filter" multiple placeholder="Categorías" data-style="warning">
      {% for cat in categories %}
        <option value="{{cat}}">{{cat}}</option>
      {% endfor %}
    </select>
    <input class="form-control" id="searchBooks" aria-label="Search" placeholder="Búsqueda"></input>
  </div>
  <div class="table-responsive m-2">
    <input id="dataURL" type="hidden" value="{% url 'webapp:books_table' %}" style="display: none;"></input>
    <table class="table table-bordered table-striped" id="dataTableBooks">
      <thead>
        <tr>
          <th>Título</th>
          <th>Autores</th>
          <th>Categorías</th>
          <th>Páginas</th>
          <th>Formato</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Título</th>
          <th>Autores</th>
          <th>Categorías</th>
          <th>Páginas</th>
          <th>Formato</th>
        </tr>
      </tfoot>
      <tbody >


      </tbody>
    </table>
  </div>
</div>

{% endblock %}


{% block links %}

<!-- Scripts for this page-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<script language="JavaScript" type="text/javascript" src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>
<script language="JavaScript" type="text/javascript" src="{% static 'webapp/books_datatable.js' %}"></script>

{% endblock %}

webapp/templates/webapp/categories.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}
    <title>BibliMoteka - Categorías</title>
{% endblock %}


{% block navbar %}
<a class="nav-link" href="{% url 'webapp:homepage' %}">Inicio</a>
<a class="nav-link active text-warning" aria-current="page" href="{% url 'webapp:categories' %}">Categorías</a>
<a class="nav-link" href="{% url 'webapp:authors' %}">Autores</a>
<a class="nav-link" href="{% url 'webapp:books' %}">Libros</a>
{% endblock %}


{% block content %}

<!-- Searchbox -->
<div class="row justify-content-md-center p-3">
  <div class="col-6">
    <div class="card text-center border-warning border-2">
      <div class="card-body text-bg-dark text-light">
          <input class="form-control" id="searchCategory" aria-label="Search" placeholder="Búsqueda" data-url="{% url 'webapp:categories' %}"
          {% if search_category %}
          value="{{ search_category }}"
          {% endif %}
          ></input>
      </div>
    </div>
  </div>
</div>

<!-- Categories -->
<div class="row row-cols-4 g-3 justify-content-md-center text-center" >
  {% for category in categories %}
  <div class="col">
    <div class="card text-bg-dark border-warning border-2 h-100">
      <div class="card-body">
        <span class="card-title">{{category.name}}</span>
      </div>
      <a class="btn btn-warning rounded-0" href="{% url 'webapp:category_books' %}?category_name={{category.name}}">Ver libros
      </a>
    </div>
  </div>
  {% endfor %}
</div>


<!-- Pagination-->

<nav aria-label="Pagination">
    <ul class="pagination justify-content-center p-3">

      {% if categories.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ categories.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&laquo;</a></li>
      {% endif %}

      {% for num in categories.paginator.page_range %}
        {% if num == categories.number %}
          <li class="page-item disabled"><a class="page-link"href="#">{{ num }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}

      {% if categories.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ categories.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&raquo;</a></li>
      {% endif %}
    </ul>
</nav>
{% endblock %}


{% block links %}

<!-- Scripts for this page-->
<script language="JavaScript" type="text/javascript" src="{% static 'webapp/search_category.js' %}"></script>

{% endblock %}

webapp/templates/webapp/category_books.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}
    <title>BibliMoteka - Categorías</title>
{% endblock %}


{% block navbar %}
<a class="nav-link" href="{% url 'webapp:homepage' %}">Inicio</a>
<a class="nav-link active text-warning" aria-current="page" href="{% url 'webapp:categories' %}">Categorías</a>
<a class="nav-link" href="{% url 'webapp:authors' %}">Autores</a>
<a class="nav-link" href="{% url 'webapp:books' %}">Libros</a>
{% endblock %}


{% block content %}

<!-- Category -->
<div class="row justify-content-md-center p-3">
  <div class="col-6"> 
    <div class="card text-center border-warning border-2">
      <div class="card-body text-bg-dark">
          <h5>{{category.name}}</h5>
      </div>
    </div>
  </div>
</div>

<!-- Books -->
<div class="row row-cols-4 g-3 justify-content-md-center text-center" >
  {% for book in books %}
  <div class="col">
      <div class="card text-bg-dark border-warning border-2 h-100">
        {% if book.file_format == 'pdf' %}
        <div class="card-img-top p-3">
          <a href="{{ book.file }}" target="_blank"> <img src="{{book.image}}" width=150 height="200"> </a>
        </div>
        {% else %}
          <a class="text-decoration-none p-5" href="{{ book.file }}" target="_blank"><h6 align="center" class="card-title text-light">
          {% if book.file_format == 'epub' %}
            EPUB
          {% else %}
            DJVU
          {% endif %}
          </h6></a>
        {% endif %}
        <div class="card-body vcenter">
          <a class="text-decoration-none" href="{{ book.file }}"><h6 class="card-title text-light">{{book.title}}</h6></a>
          <p class="text-secondary">{{ book.pages }} páginas</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item text-secondary text-bg-dark border-warning">
            {% for author in book.authors.all %}
            - <a class="link-secondary" href="{% url 'webapp:author_books' %}?author_name={{author.name}}">{{ author.name }}</a>
            {% endfor %}
          </li>
          <li class="list-group-item text-secondary text-bg-dark border-warning">
            {% for category in book.categories.all %}
            #<a class="link-secondary" href="{% url 'webapp:category_books' %}?category_name={{category.name}}">{{ category.name }}</a>
            {% endfor %}
          </li>
        </ul>
        <a class="btn btn-warning rounded-0" href="{{ book.file }}" target="_blank">Enlace</a>
      </div>
  </div>
  {% endfor %}
</div>


<!-- Pagination-->

<nav aria-label="Pagination">
    <ul class="pagination justify-content-center p-3">

      {% if books.has_previous %}
      <li class="page-item"><a class="page-link" href="?category_name={{category.name}}&page={{ books.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&laquo;</a></li>
      {% endif %}

      {% for num in books.paginator.page_range %}
        {% if num == books.number %}
          <li class="page-item disabled"><a class="page-link"href="#">{{ num }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?category_name={{category.name}}&page={{ num }}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}

      {% if books.has_next %}
      <li class="page-item"><a class="page-link" href="?category_name={{category.name}}&page={{ books.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#!">&raquo;</a></li>
      {% endif %}
    </ul>
</nav>
{% endblock %}

webapp/templates/webapp/index.html
{% extends "webapp/base.html" %}
{% load static %}


{% block title %}
    <title>BiblioMoteka - Inicio</title>
{% endblock %}


{% block navbar %}
<a class="nav-link active text-warning" aria-current="page" href="{% url 'webapp:homepage' %}">Inicio</a>
<a class="nav-link" href="{% url 'webapp:categories' %}">Categorías</a>
<a class="nav-link" href="{% url 'webapp:authors' %}">Autores</a>
<a class="nav-link" href="{% url 'webapp:books' %}">Libros</a>
{% endblock %}


{% block content %}
<div class="row row-cols-4 g-3 justify-content-md-center text-center" >
	{% for book in books %}
	<div class="col">
		<div class="card text-bg-dark border-warning border-2 h-100">
			{% if book.file_format == 'pdf' %}
			<div class="card-img-top p-3">
				<a href="{{ book.file }}" target="_blank"> <img src="{{book.image}}" width=150 height="200"> </a>
			</div>
			{% else %}
			<a class="text-decoration-none p-5" href="{{ book.file }}" target="_blank"><h6 align="center" class="card-title text-light">
				{% if book.file_format == 'epub' %}
					EPUB
				{% else %}
					DJVU
				{% endif %}
			</h6></a>
			{% endif %}
			<div class="card-body md-auto">
				<a class="text-decoration-none" href="{{ book.file }}"target="_blank"><h6 class="card-title text-light">{{book.title}}</h6></a>
				{% if book.image %}
				<p class="text-secondary">{{ book.pages }} páginas</p>
				{% endif %}
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item text-secondary text-bg-dark border-warning">
					{% for author in book.authors.all %}
					- <a class="link-secondary" href="{% url 'webapp:author_books' %}?author_name={{author.name}}">{{ author.name }}</a>
					{% endfor %}
				</li>
				<li class="list-group-item text-secondary text-bg-dark border-warning">
					{% for category in book.categories.all %}
					#<a class="link-secondary" href="{% url 'webapp:category_books' %}?category_name={{category.name}}">{{ category.name }}</a>
					{% endfor %}
				</li>
			</ul>
			<a class="btn btn-warning rounded-0" href="{{ book.file }}" target="_blank">Enlace</a>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}